
training:
  data: first_100k_evaluations.csv
  batch_size: 32

model: 
  _target_: model.GNNModel
  #_target_: model.AttentionEPDGNN
  in_channels: 13
  hidden_channels: 64
  out_channels: 128

loss:
  # for regression task
  # _target_: torch.nn.MSELoss
  _target_: torch.nn.CrossEntropyLoss
